spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false


springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html