CREATE TABLE IF NOT EXISTS USER_INFO (name varchar(255), salary number(20,3));
TRUNCATE TABLE USER_INFO;
INSERT INTO USER_INFO VALUES ('ooi1', 2000);
INSERT INTO USER_INFO VALUES ('ooi2', 1000);
INSERT INTO USER_INFO VALUES ('ooi3', 5000);
INSERT INTO USER_INFO VALUES ('ooi4', 3000);
INSERT INTO USER_INFO VALUES ('ooi5', 3000);
